#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright © 2017 Matthew Stone <mstone5@mgh.harvard.edu>
# Distributed under terms of the MIT license.

"""
SVTools: Utilities for manipulating structural variation

usage: svtools [-h] <subcommand> [options]

[ Preprocessing ]
    standardize   Convert SV calls to a standardized format.

[ Algorithm integration ]
    vcfcluster    Cluster SV calls from a list of VCFs. (Generally PE/SR.)
    bedcluster    Cluster SV calls from a BED. (Generally depth.)

[ Uncategorized or not yet implemented ]
    bincov        Calculate normalized genome-wide depth of coverage.
    rdtest        Calculate comparative coverage statistics at CNV sites.
"""

import argparse
import sys
import svtools.cli as cli


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        usage=argparse.SUPPRESS,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('subcommand', help=argparse.SUPPRESS)
    args = parser.parse_args(sys.argv[1:2])

    if not hasattr(cli, args.subcommand):
        print('Unrecognized command: {0}'.format(args.subcommand))
        parser.print_help()
        sys.exit(1)

    getattr(cli, args.subcommand)(sys.argv[2:])

if __name__ == '__main__':
    main()
