#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright © 2017 Matthew Stone <mstone5@mgh.harvard.edu>
# Distributed under terms of the MIT license.

"""
SVTools: Utilities for manipulating structural variation

[ Preprocessing ]
    standardize   Convert SV calls to a standardized format.

[ Algorithm integration ]
    vcfcluster    Cluster SV calls from a list of VCFs. (Generally PE/SR.)
    bedcluster    Cluster SV calls from a BED. (Generally depth.)

[ Uncategorized ]
    bincov        Calculate normalized genome-wide depth of coverage.
    rdtest        Calculate comparative coverage statistics at CNV sites.
"""

import argparse
import sys
import svtools


class SVTools:
    def __init__(self):
        parser = argparse.ArgumentParser(
            description=__doc__,
            formatter_class=argparse.RawDescriptionHelpFormatter)
        parser.add_argument('subcommand', help=argparse.SUPPRESS)
        args = parser.parse_args(sys.argv[1:2])

        if not hasattr(self, args.command):
            print('Unrecognized command: {0}'.format(args.command))
            parser.print_help()
            sys.exit(1)

        getattr(self, args.command)()


if __name__ == '__main__':
    SVTools()
